import os, glob
env = Environment()

# Short messages while compiling and linking.
env.Append(CXXCOMSTR = "Compiling static object $TARGET")
env.Append(LINKCOMSTR = "Linking $TARGET")
env.Append(SHCXXCOMSTR = "Compiling shared object $TARGET")
env.Append(SHLINKCOMSTR = "Linking shared $TARGET" )


# CXXFLAGS
if ARGUMENTS.get('debug', 0):
    env.Append(CXXFLAGS = ['-g'])
    build_dir = 'debug/'
else:
    build_dir = 'release/'

env.BuildDir(build_dir, 'src/', duplicate=0)

env.Append(CXXFLAGS = ['-march=native'])
env.Append(CXXFLAGS = ['-Wno-write-strings'])
# env.Append(LINKFLAGS = ['-Wl,--no-undefined'])


# Headers and libs
env['CPPPATH'] = [ build_dir,
				  'src',
                  '../src',
                  '../',
                  '/usr/include/opencv', '/usr/local/include/opencv',
                  '/usr/local/include/boost']

env['LIBPATH'] = ['/usr/local/lib',
                  '/usr/lib',
				  './']

env['LIBS'] = [
    'cxcore',
    'cv',
    'cvaux',
    'boost_program_options'
]

# Common sources.
# common_src = env.Glob( build_dir + '*.cpp')

# Face detector sources.
face_haar_src = env.Glob( build_dir + 'face_detector_plugin.cpp')

# Shared lib
env.SharedLibrary(target = 'zm_plugin_face_haar', source = face_haar_src)

